name: CI/CD Pipeline

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checking out the code
      - name: Checkout code
        uses: actions/checkout@v2
        
      # Setting up the C environment
      - name: Setup C environment
        run: sudo apt-get install -y build-essential rpm
        
      # Linting using clang-format
      - name: Lint code
        run: |
          sudo apt-get install -y clang-format
          find . -name '*.[ch]' | xargs clang-format -i --style=Google
          git diff --exit-code
        
      # SAST using Clang Static Analyzer
      - name: Static Application Security Testing
        run: |
          sudo apt-get install -y clang-tools
          scan-build make

      # Replace version placeholder in the spec file
      - name: Set version in the spec file
        run: sed -i 's/%VERSION_PLACEHOLDER%/${{ steps.get_version.outputs.VERSION }}/g' senpai.spec
        
      # Building RPM package
      - name: Build RPM package
        uses: naveenramasamy/rpmbuild-action@master
        with:
          specFile: 'senpai.spec'
